# Site settings
title: Firdaus & Zya
email: firdaus1453@gmail.com
url: https://firdaus1453.github.io
description: Senin, 21 Juni 2021

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: firdaus1453.me

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https:fb.me/firdaus1453
  - title: github
    url: https://github.com/firdaus1453

# Build settings
markdown: kramdown
permalink: pretty
